/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import View.BanHangJPanel;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Model_khachHang;
import responsitory.KhachHangRepository;

/**
 *
 * @author Admin
 */
public class BHChonKH extends javax.swing.JFrame {

    private BanHangJPanel BH;
    private Model_khachHang selectedCustomer;

    private DefaultTableModel mol = new DefaultTableModel();
    private KhachHangRepository rp = new KhachHangRepository();
    private int i = 1;

    /**
     * Creates new form BHChonKH
     */
    public BHChonKH(BanHangJPanel bh) {
        initComponents();
        this.setLocationRelativeTo(null);
        mol = (DefaultTableModel) tbl_ChonKH.getModel();
        this.BH = bh;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ChonKH = new javax.swing.JTable();
        txt_timKiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        tbl_ChonKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Khách Hàng", "Tên Khách Hàng", "Ngày Sinh", "Giới Tính", "Địa Chỉ", "Email", "SĐT"
            }
        ));
        tbl_ChonKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_ChonKHMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ChonKH);

        txt_timKiem.setToolTipText("Tìm Kiếm Theo Tên Hoặc Số Điện Thoại!");
        txt_timKiem.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txt_timKiemMouseMoved(evt);
            }
        });
        txt_timKiem.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                txt_timKiemMouseWheelMoved(evt);
            }
        });
        txt_timKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_timKiemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_timKiemMouseEntered(evt);
            }
        });
        txt_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemActionPerformed(evt);
            }
        });

        jButton1.setText("Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Làm Mới");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_ChonKHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ChonKHMousePressed

        if (evt.getClickCount() == 2) {  // Xử lý sự kiện nhấp đôi chuột
            int selectedRow = tbl_ChonKH.getSelectedRow();
            if (selectedRow >= 0) {
                String tenKH = tbl_ChonKH.getValueAt(selectedRow, 1).toString();
                String sdt = (tbl_ChonKH.getValueAt(selectedRow, 6).toString());

                // Cập nhật thông tin khách hàng vào panel trong BanHang
                if (BH != null) {
                    BH.updateCustomerInfo(sdt, tenKH);
                }
                this.setVisible(false);  // Đóng cửa sổ chọn khách hàng
            }
        }


    }//GEN-LAST:event_tbl_ChonKHMousePressed

    private void txt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tenKH = txt_timKiem.getText();
        String sđt = txt_timKiem.getText();
        updateTable(rp.timKiemChon(tenKH, sđt));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        updateTable(rp.getAll());
        txt_timKiem.setText(null);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_timKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_timKiemMouseEntered
        // TODO add your handling code here:
        String tenKH = txt_timKiem.getText();
        String sđt = txt_timKiem.getText();
        updateTable(rp.timKiemChon(tenKH, sđt));
    }//GEN-LAST:event_txt_timKiemMouseEntered

    private void txt_timKiemMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_timKiemMouseMoved
        // TODO add your handling code here:
        txt_timKiem.setToolTipText("Tìm Kiếm Theo Tên Hoặc Số Điện Thoại!");
    }//GEN-LAST:event_txt_timKiemMouseMoved

    private void txt_timKiemMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_txt_timKiemMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemMouseWheelMoved

    private void txt_timKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_timKiemMouseClicked
        // TODO add your handling code here:
        txt_timKiem.setToolTipText("Tìm Kiếm Theo Tên Hoặc Số Điện Thoại!");

    }//GEN-LAST:event_txt_timKiemMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ChonKH;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables

    public void updateTable(ArrayList<Model_khachHang> customers) {
        mol.setRowCount(0); // Xóa các hàng cũ              
        for (Model_khachHang kh : customers) {
            mol.addRow(new Object[]{kh.getId(), kh.getTen(), kh.getNgaySinh(), kh.isGioiTinh() ? "Nam" : "Nữ", kh.getDiaChi(), kh.getEmail(), kh.getSdt()});
        }
    }
}
