package View;

import model.ChatLieu;
import model.DanhMuc;
import model.MauSac;
import model.Size;
import model.ThuongHieu;
import responsitory.ChatLieuRepo;
import responsitory.DanhMucRepo;
import responsitory.MauSacRepo;
import responsitory.SizeRepo;
import responsitory.ThuongHieuRepo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SanPhamViewModel;
import responsitory.SPCTRepo;
import responsitory.SanPhamRepo;

/**
 *
 * @author Thanh Thao
 */
public class ThuocTinhView extends javax.swing.JFrame {

    private ChatLieuRepo clRepo = new ChatLieuRepo();
    private DanhMucRepo dmRepo = new DanhMucRepo();
    private MauSacRepo msRepo = new MauSacRepo();
    private SizeRepo szRepo = new SizeRepo();
    private ThuongHieuRepo thRepo = new ThuongHieuRepo();
    private SanPhamJPanel sp = new SanPhamJPanel();
    private SanPhamRepo sanPhamRepo = new SanPhamRepo();
    private SPCTRepo spctRepo = new SPCTRepo();

    private List<ThuongHieu> lstTH = new ArrayList<>();
    private List<ChatLieu> lstCL = new ArrayList<>();
    private List<DanhMuc> lstDM = new ArrayList<>();
    private List<Size> lstSZ = new ArrayList<>();
    private List<MauSac> lstMS = new ArrayList<>();
   
    public ThuocTinhView() {
        initComponents();
        loadTable();
        sp.initCbo();
    }
    

    public void loadTable() {
        loadDataCL((ArrayList<ChatLieu>) clRepo.getAll());
        loadDataDM((ArrayList<DanhMuc>) dmRepo.getAll());
        loadDataMS((ArrayList<MauSac>) msRepo.getAll());
        loadDataSZ((ArrayList<Size>) szRepo.getAll());
        loadDataTH((ArrayList<ThuongHieu>) thRepo.getAll());
    }
  

    public void loadDataCL(ArrayList<ChatLieu> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblCL.getModel();
        defaultTableModel.setRowCount(0);
        lstCL = list; //
        for (ChatLieu cl : list) {
            defaultTableModel.addRow(new Object[]{
                cl.getTenCL(),
                cl.getTrangThai() ? "Hoạt Động" : "Không Hoạt Động"
            });
        }
    }

    public void loadDataDM(ArrayList<DanhMuc> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblDM.getModel();
        defaultTableModel.setRowCount(0);
        lstDM = list; //
        for (DanhMuc dm : list) {
            defaultTableModel.addRow(new Object[]{
                dm.getTenDM(),
                dm.getTrangThai() ? "Hoạt Động" : "Không Hoạt Động"
            });
        }
    }

    public void loadDataMS(ArrayList<MauSac> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblMS.getModel();
        defaultTableModel.setRowCount(0);
        lstMS = list; //
        for (MauSac ms : list) {
            defaultTableModel.addRow(new Object[]{
                ms.getTenMS(),
                ms.getTrangThai() ? "Hoạt Động" : "Không Hoạt Động"
            });
        }
    }

    public void loadDataSZ(ArrayList<Size> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblSize.getModel();
        defaultTableModel.setRowCount(0);
        lstSZ = list; //
        for (Size sz : list) {
            defaultTableModel.addRow(new Object[]{
                sz.getTenSize(),
                sz.getTrangThai() ? "Hoạt Động" : "Không Hoạt Động"
            });
        }
    }

    public void loadDataTH(ArrayList<ThuongHieu> list) {
    DefaultTableModel defaultTableModel = (DefaultTableModel) tblThuongHieu.getModel();
    defaultTableModel.setRowCount(0);
    lstTH = list; // Cập nhật danh sách lstTH
    for (ThuongHieu th : list) {
        defaultTableModel.addRow(new Object[]{
            th.getTenTH(),
            th.getTrangThai() ? "Hoạt Động" : "Không Hoạt Động"
        });
    }
}
    private void clearTH() {
        txtTenTH.setText("");
        rdoTrangThai.setSelected(true);
    }
    private void clearCL() {
        txtTenCL.setText("");
        rdoCL.setSelected(true);
    }
    private void clearDM() {
        txtDM.setText("");
        rdoDM.setSelected(true);
    }
    private void clearMS() {
        txtMS.setText("");
        rdoMS.setSelected(true);
    }
    private void clearSZ() {
        txtSize.setText("");
        rdoSize.setSelected(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThuongHieu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTenTH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rdoTrangThai = new javax.swing.JRadioButton();
        rdoTrangThai11 = new javax.swing.JRadioButton();
        btnThemTH = new javax.swing.JButton();
        btnXoaTH = new javax.swing.JButton();
        btnClearTH = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCL = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtTenCL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdoCL = new javax.swing.JRadioButton();
        rdoCL1 = new javax.swing.JRadioButton();
        btnThemCL = new javax.swing.JButton();
        btnXoaCL = new javax.swing.JButton();
        btnClearCL = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDM = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtDM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdoDM = new javax.swing.JRadioButton();
        rdoDM1 = new javax.swing.JRadioButton();
        btnThemDM = new javax.swing.JButton();
        btnXoaDM = new javax.swing.JButton();
        btnClearDM = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSize = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rdoSize = new javax.swing.JRadioButton();
        rdoSize1 = new javax.swing.JRadioButton();
        btnThemSize = new javax.swing.JButton();
        btnXoaSize = new javax.swing.JButton();
        btnClearSize = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMS = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtMS = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rdoMS = new javax.swing.JRadioButton();
        rdoMS1 = new javax.swing.JRadioButton();
        btnThemMS = new javax.swing.JButton();
        btnXoaMS = new javax.swing.JButton();
        btnClearMS = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản Lý Thuộc Tính", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblThuongHieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên Thương Hiệu", "Trạng Thái"
            }
        ));
        tblThuongHieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThuongHieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThuongHieu);

        jLabel1.setText("Tên Thương Hiệu");

        jLabel2.setText("Trạng Thái");

        rdoTrangThai.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoTrangThai);
        rdoTrangThai.setText("Hoạt Động");

        rdoTrangThai11.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoTrangThai11);
        rdoTrangThai11.setText("Không Hoạt Động");

        btnThemTH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemTH.setText("Thêm");
        btnThemTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTHActionPerformed(evt);
            }
        });

        btnXoaTH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaTH.setText("Xóa");
        btnXoaTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTHActionPerformed(evt);
            }
        });

        btnClearTH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearTH.setText("Clear");
        btnClearTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(60, 60, 60)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThemTH, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdoTrangThai)
                                        .addGap(127, 127, 127)
                                        .addComponent(rdoTrangThai11))
                                    .addComponent(txtTenTH, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnXoaTH, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClearTH, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoTrangThai)
                        .addComponent(rdoTrangThai11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTH)
                    .addComponent(btnXoaTH)
                    .addComponent(btnClearTH))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Thương Hiệu", jPanel1);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tblCL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên Chất Liệu", "Trạng Thái"
            }
        ));
        tblCL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCLMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCL);

        jLabel3.setText("Tên Chất Liệu");

        jLabel4.setText("Trạng Thái");

        rdoCL.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rdoCL);
        rdoCL.setText("Hoạt Động");

        rdoCL1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rdoCL1);
        rdoCL1.setText("Không Hoạt Động");

        btnThemCL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemCL.setText("Thêm");
        btnThemCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCLActionPerformed(evt);
            }
        });

        btnXoaCL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaCL.setText("Xóa");
        btnXoaCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCLActionPerformed(evt);
            }
        });

        btnClearCL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearCL.setText("Clear");
        btnClearCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(60, 60, 60)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnThemCL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(rdoCL)
                                        .addGap(127, 127, 127)
                                        .addComponent(rdoCL1))
                                    .addComponent(txtTenCL, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnXoaCL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClearCL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoCL)
                        .addComponent(rdoCL1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemCL)
                    .addComponent(btnXoaCL)
                    .addComponent(btnClearCL))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Chất Liệu", jPanel2);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        tblDM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên Danh Mục", "Trạng Thái"
            }
        ));
        tblDM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDMMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDM);

        jLabel5.setText("Tên Danh Mục");

        jLabel6.setText("Trạng Thái");

        rdoDM.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(rdoDM);
        rdoDM.setText("Hoạt Động");

        rdoDM1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(rdoDM1);
        rdoDM1.setText("Không Hoạt Động");

        btnThemDM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemDM.setText("Thêm");
        btnThemDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDMActionPerformed(evt);
            }
        });

        btnXoaDM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaDM.setText("Xóa");
        btnXoaDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDMActionPerformed(evt);
            }
        });

        btnClearDM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearDM.setText("Clear");
        btnClearDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearDMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(60, 60, 60)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btnThemDM, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(rdoDM)
                                        .addGap(127, 127, 127)
                                        .addComponent(rdoDM1))
                                    .addComponent(txtDM, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnXoaDM, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClearDM, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoDM)
                        .addComponent(rdoDM1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDM)
                    .addComponent(btnXoaDM)
                    .addComponent(btnClearDM))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Danh Mục", jPanel3);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        tblSize.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên Size", "Trạng Thái"
            }
        ));
        tblSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSizeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSize);

        jLabel7.setText("Tên Size");

        jLabel8.setText("Trạng Thái");

        rdoSize.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(rdoSize);
        rdoSize.setText("Hoạt Động");

        rdoSize1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(rdoSize1);
        rdoSize1.setText("Không Hoạt Động");

        btnThemSize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemSize.setText("Thêm");
        btnThemSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSizeActionPerformed(evt);
            }
        });

        btnXoaSize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaSize.setText("Xóa");
        btnXoaSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSizeActionPerformed(evt);
            }
        });

        btnClearSize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearSize.setText("Clear");
        btnClearSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(60, 60, 60)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btnThemSize, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(rdoSize)
                                        .addGap(127, 127, 127)
                                        .addComponent(rdoSize1))
                                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnXoaSize, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClearSize, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoSize)
                        .addComponent(rdoSize1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSize)
                    .addComponent(btnXoaSize)
                    .addComponent(btnClearSize))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Size", jPanel4);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        tblMS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên Màu Sắc", "Trạng Thái"
            }
        ));
        tblMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMSMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblMS);

        jLabel9.setText("Tên Màu Sắc");

        jLabel10.setText("Trạng Thái");

        rdoMS.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(rdoMS);
        rdoMS.setText("Hoạt Động");

        rdoMS1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(rdoMS1);
        rdoMS1.setText("Không Hoạt Động");

        btnThemMS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemMS.setText("Thêm");
        btnThemMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMSActionPerformed(evt);
            }
        });

        btnXoaMS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaMS.setText("Xóa");
        btnXoaMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMSActionPerformed(evt);
            }
        });

        btnClearMS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearMS.setText("Clear");
        btnClearMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearMSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(60, 60, 60)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(btnThemMS, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(rdoMS)
                                        .addGap(127, 127, 127)
                                        .addComponent(rdoMS1))
                                    .addComponent(txtMS, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXoaMS, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(btnClearMS, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoMS)
                        .addComponent(rdoMS1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMS)
                    .addComponent(btnXoaMS)
                    .addComponent(btnClearMS))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Màu Sắc", jPanel5);

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnThemCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCLActionPerformed

        ChatLieu cl = new ChatLieu();
        String tenCL = txtTenCL.getText();
        if (tenCL.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Tên Chất Liệu");
            return;
        }
        // Kiểm tra xem tên thương hiệu đã tồn tại hay chưa
        if (clRepo.TonTaiTenCL(tenCL)) {
            JOptionPane.showMessageDialog(this, "Tên chất liệu đã tồn tại");
            return;
        }
        cl.setTenCL(txtTenCL.getText());
        if (rdoCL.isSelected()) {
            cl.setTrangThai(true); // Hoạt động
        } else {
            cl.setTrangThai(false); // Không hoạt động
        }

        if (clRepo.add(cl) == true) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại ");
        }
        loadDataCL((ArrayList<ChatLieu>) clRepo.getAll());
        sp.loadComboBoxChatLieu((ArrayList<ChatLieu>) clRepo.getAll());
//        sp.loadData((ArrayList<SanPhamViewModel>) sanPhamRepo.getAll());
        sp.initCbo();
    }//GEN-LAST:event_btnThemCLActionPerformed

    private void btnThemTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTHActionPerformed
        ThuongHieu th = new ThuongHieu();
        String tenTH = txtTenTH.getText().trim();

        // Kiểm tra tên thương hiệu
        if (tenTH.length() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên thương hiệu");
            return;
        }

        // Kiểm tra xem tên thương hiệu đã tồn tại hay chưa
        if (thRepo.TonTaiTenTH(tenTH)) {
            JOptionPane.showMessageDialog(this, "Tên thương hiệu đã tồn tại");
            return;
        }

        // Thêm thông tin vào đối tượng th
        th.setTenTH(tenTH);
        if (rdoTrangThai.isSelected()) {
            th.setTrangThai(true); // Hoạt động
        } else {
            th.setTrangThai(false); // Không hoạt động
        }

        // Thực hiện thêm vào cơ sở dữ liệu
        if (thRepo.add(th)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }

        // Load lại dữ liệu
        loadDataTH((ArrayList<ThuongHieu>) thRepo.getAll());
        sp.initCbo();
    }//GEN-LAST:event_btnThemTHActionPerformed

    private void btnThemDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDMActionPerformed
        DanhMuc dm = new DanhMuc();
        String tenDM = txtDM.getText();
        if (tenDM.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Tên Danh Mục");
            return;
        }
        // Kiểm tra xem tên thương hiệu đã tồn tại hay chưa
        if (dmRepo.TonTaiTenDM(tenDM)) {
            JOptionPane.showMessageDialog(this, "Tên danh mục đã tồn tại");
            return;
        }
        dm.setTenDM(txtDM.getText());
        if (rdoDM.isSelected()) {
            dm.setTrangThai(true); // Hoạt động
        } else {
            dm.setTrangThai(false); // Không hoạt động
        }

        if (dmRepo.add(dm) == true) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại ");
        }
        loadDataDM((ArrayList<DanhMuc>) dmRepo.getAll());
        sp.initCbo();
    }//GEN-LAST:event_btnThemDMActionPerformed

    private void btnThemSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSizeActionPerformed
        Size sz = new Size();
        String tenSZ = txtSize.getText();
        if (tenSZ.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Tên Danh Mục");
            return;
        }
        // Kiểm tra xem tên thương hiệu đã tồn tại hay chưa
        if (szRepo.TonTaiTenSZ(tenSZ)) {
            JOptionPane.showMessageDialog(this, "Tên size đã tồn tại");
            return;
        }
        sz.setTenSize(txtSize.getText());
        if (rdoSize.isSelected()) {
            sz.setTrangThai(true); // Hoạt động
        } else {
            sz.setTrangThai(false); // Không hoạt động
        }

        if (szRepo.add(sz) == true) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại ");
        }
        loadDataSZ((ArrayList<Size>) szRepo.getAll());
        sp.initCbo();
    }//GEN-LAST:event_btnThemSizeActionPerformed

    private void btnThemMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMSActionPerformed
        MauSac ms = new MauSac();
        String tenMS = txtMS.getText();
        if (tenMS.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Tên Danh Mục");
            return;
        }
        // Kiểm tra xem tên thương hiệu đã tồn tại hay chưa
        if (msRepo.TonTaiTenMS(tenMS)) {
            JOptionPane.showMessageDialog(this, "Tên màu sắc đã tồn tại");
            return;
        }
        ms.setTenMS(txtMS.getText());
        if (rdoMS.isSelected()) {
            ms.setTrangThai(true); // Hoạt động
        } else {
            ms.setTrangThai(false); // Không hoạt động
        }

        if (msRepo.add(ms) == true) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại ");
        }
        loadDataMS((ArrayList<MauSac>) msRepo.getAll());
        sp.initCbo();

    }//GEN-LAST:event_btnThemMSActionPerformed

    private void tblThuongHieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThuongHieuMouseClicked
        int row = tblThuongHieu.getSelectedRow();

        txtTenTH.setText((String) tblThuongHieu.getValueAt(row, 0));

        if (tblThuongHieu.getValueAt(row, 1).toString().equalsIgnoreCase("Hoạt Động")) {
            rdoTrangThai.setSelected(true);
        } else {
            rdoTrangThai11.setSelected(true);
        }
    }//GEN-LAST:event_tblThuongHieuMouseClicked

    private void btnClearTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTHActionPerformed
        clearTH();
    }//GEN-LAST:event_btnClearTHActionPerformed

    private void btnClearCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCLActionPerformed
        clearCL();
    }//GEN-LAST:event_btnClearCLActionPerformed

    private void btnClearDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearDMActionPerformed
        clearDM();
    }//GEN-LAST:event_btnClearDMActionPerformed

    private void btnClearSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSizeActionPerformed
        clearSZ();
    }//GEN-LAST:event_btnClearSizeActionPerformed

    private void btnClearMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearMSActionPerformed
        clearMS();
    }//GEN-LAST:event_btnClearMSActionPerformed

    private void tblCLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCLMouseClicked
        int row = tblCL.getSelectedRow();

        txtTenCL.setText((String) tblCL.getValueAt(row, 0));

        if (tblCL.getValueAt(row, 1).toString().equalsIgnoreCase("Hoạt Động")) {
            rdoCL.setSelected(true);
        } else {
            rdoCL1.setSelected(true);
        }
//        sp.loadComboBoxChatLieu((ArrayList<ChatLieu>) clRepo.getAll());
//        sp.loadData((ArrayList<SanPhamViewModel>) sanPhamRepo.getAll());
    }//GEN-LAST:event_tblCLMouseClicked

    private void tblDMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDMMouseClicked
        int row = tblDM.getSelectedRow();

        txtDM.setText((String) tblDM.getValueAt(row, 0));

        if (tblDM.getValueAt(row, 1).toString().equalsIgnoreCase("Hoạt Động")) {
            rdoDM.setSelected(true);
        } else {
            rdoDM1.setSelected(true);
        }
    }//GEN-LAST:event_tblDMMouseClicked

    private void tblSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSizeMouseClicked
        int row = tblSize.getSelectedRow();

        txtSize.setText((String) tblSize.getValueAt(row, 0));

        if (tblSize.getValueAt(row, 1).toString().equalsIgnoreCase("Hoạt Động")) {
            rdoSize.setSelected(true);
        } else {
            rdoSize1.setSelected(true);
        }
    }//GEN-LAST:event_tblSizeMouseClicked

    private void tblMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMSMouseClicked
        int row = tblMS.getSelectedRow();

        txtMS.setText((String) tblMS.getValueAt(row, 0));

        if (tblMS.getValueAt(row, 1).toString().equalsIgnoreCase("Hoạt Động")) {
            rdoMS.setSelected(true);
        } else {
            rdoMS1.setSelected(true);
        }
    }//GEN-LAST:event_tblMSMouseClicked

    private void btnXoaTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTHActionPerformed
        int index = tblThuongHieu.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn");
            return;
        }
        int chk = JOptionPane.showConfirmDialog(this, "Xác Nhận Xóa");
        if (chk != JOptionPane.YES_OPTION) {
            return;
        }
        ThuongHieu OBJ = lstTH.get(index);
        if (thRepo.Xoa(OBJ.getId())) {
            JOptionPane.showMessageDialog(this, "Xóa Thành Công");
        } else {
            JOptionPane.showMessageDialog(this, " Xóa Thất Bại");
        }
        loadDataTH((ArrayList<ThuongHieu>) thRepo.getAll());
    }//GEN-LAST:event_btnXoaTHActionPerformed

    private void btnXoaCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCLActionPerformed
        int index = tblCL.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn");
            return;
        }
        int chk = JOptionPane.showConfirmDialog(this, "Xác Nhận Xóa");
        if (chk != JOptionPane.YES_OPTION) {
            return;
        }
        ChatLieu OBJ = lstCL.get(index);
        if (clRepo.Xoa(OBJ.getId())) {
            JOptionPane.showMessageDialog(this, "Xóa Thành Công");
        } else {
            JOptionPane.showMessageDialog(this, " Xóa Thất Bại");
        }
        loadDataCL((ArrayList<ChatLieu>) clRepo.getAll());
    }//GEN-LAST:event_btnXoaCLActionPerformed

    private void btnXoaDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDMActionPerformed
        int index = tblDM.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn");
            return;
        }
        int chk = JOptionPane.showConfirmDialog(this, "Xác Nhận Xóa");
        if (chk != JOptionPane.YES_OPTION) {
            return;
        }
        DanhMuc OBJ = lstDM.get(index);
        if (dmRepo.Xoa(OBJ.getId())) {
            JOptionPane.showMessageDialog(this, "Xóa Thành Công");
        } else {
            JOptionPane.showMessageDialog(this, " Xóa Thất Bại");
        }
        loadDataDM((ArrayList<DanhMuc>) dmRepo.getAll());
    }//GEN-LAST:event_btnXoaDMActionPerformed

    private void btnXoaSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSizeActionPerformed
        int index = tblSize.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn");
            return;
        }
        int chk = JOptionPane.showConfirmDialog(this, "Xác Nhận Xóa");
        if (chk != JOptionPane.YES_OPTION) {
            return;
        }
        Size OBJ = lstSZ.get(index);
        if (szRepo.Xoa(OBJ.getId())) {
            JOptionPane.showMessageDialog(this, "Xóa Thành Công");
        } else {
            JOptionPane.showMessageDialog(this, " Xóa Thất Bại");
        }
        loadDataSZ((ArrayList<Size>) szRepo.getAll());
    }//GEN-LAST:event_btnXoaSizeActionPerformed

    private void btnXoaMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMSActionPerformed
        int index = tblMS.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn");
            return;
        }
        int chk = JOptionPane.showConfirmDialog(this, "Xác Nhận Xóa");
        if (chk != JOptionPane.YES_OPTION) {
            return;
        }
        MauSac OBJ = lstMS.get(index);
        if (msRepo.Xoa(OBJ.getId())) {
            JOptionPane.showMessageDialog(this, "Xóa Thành Công");
        } else {
            JOptionPane.showMessageDialog(this, " Xóa Thất Bại");
        }
        loadDataMS((ArrayList<MauSac>) msRepo.getAll());
    }//GEN-LAST:event_btnXoaMSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuocTinhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuocTinhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuocTinhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuocTinhView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThuocTinhView().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearCL;
    private javax.swing.JButton btnClearDM;
    private javax.swing.JButton btnClearMS;
    private javax.swing.JButton btnClearSize;
    private javax.swing.JButton btnClearTH;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnThemCL;
    private javax.swing.JButton btnThemDM;
    private javax.swing.JButton btnThemMS;
    private javax.swing.JButton btnThemSize;
    private javax.swing.JButton btnThemTH;
    private javax.swing.JButton btnXoaCL;
    private javax.swing.JButton btnXoaDM;
    private javax.swing.JButton btnXoaMS;
    private javax.swing.JButton btnXoaSize;
    private javax.swing.JButton btnXoaTH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdoCL;
    private javax.swing.JRadioButton rdoCL1;
    private javax.swing.JRadioButton rdoDM;
    private javax.swing.JRadioButton rdoDM1;
    private javax.swing.JRadioButton rdoMS;
    private javax.swing.JRadioButton rdoMS1;
    private javax.swing.JRadioButton rdoSize;
    private javax.swing.JRadioButton rdoSize1;
    private javax.swing.JRadioButton rdoTrangThai;
    private javax.swing.JRadioButton rdoTrangThai11;
    private javax.swing.JTable tblCL;
    private javax.swing.JTable tblDM;
    private javax.swing.JTable tblMS;
    private javax.swing.JTable tblSize;
    private javax.swing.JTable tblThuongHieu;
    private javax.swing.JTextField txtDM;
    private javax.swing.JTextField txtMS;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtTenCL;
    private javax.swing.JTextField txtTenTH;
    // End of variables declaration//GEN-END:variables
}
